# Generated by Django 2.2.1 on 2019-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='like',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='likefolder',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
    ]
