# Generated by Django 2.2.3 on 2019-07-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190621_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', '文章'), ('wiki', 'wiki')], db_index=True, default='article', max_length=50, verbose_name='类型(wiki/文章)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.SmallIntegerField(db_index=True, default=1, verbose_name='文章状态(1-5)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('原创', '原创'), ('转载', '转载'), ('翻译', '翻译'), ('笔记', '笔记')], db_index=True, max_length=50, verbose_name='种类(文章/原创/笔记)'),
        ),
    ]
