# Generated by Django 2.2.3 on 2019-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190720_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', '文章'), ('wiki', 'wiki')], db_index=True, default='article', max_length=50, verbose_name='类型(wiki/文章)'),
        ),
    ]
