# Generated by Django 2.2.1 on 2019-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间'),
        ),
    ]
